/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSavedSearchParameters
 */
export interface CreateSavedSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    search: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    earliestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    latestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    sharing?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSavedSearchParameters
     */
    isScheduled?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreateSavedSearchParameters
     */
    cronSchedule?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSavedSearchParameters
     */
    isVisible?: boolean;
}

/**
 * Check if a given object implements the CreateSavedSearchParameters interface.
 */
export function instanceOfCreateSavedSearchParameters(value: object): value is CreateSavedSearchParameters {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('search' in value) || value['search'] === undefined) return false;
    return true;
}

export function CreateSavedSearchParametersFromJSON(json: any): CreateSavedSearchParameters {
    return CreateSavedSearchParametersFromJSONTyped(json, false);
}

export function CreateSavedSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSavedSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'search': json['search'],
        'description': json['description'] == null ? undefined : json['description'],
        'earliestTime': json['earliest_time'] == null ? undefined : json['earliest_time'],
        'latestTime': json['latest_time'] == null ? undefined : json['latest_time'],
        'app': json['app'] == null ? undefined : json['app'],
        'sharing': json['sharing'] == null ? undefined : json['sharing'],
        'isScheduled': json['is_scheduled'] == null ? undefined : json['is_scheduled'],
        'cronSchedule': json['cron_schedule'] == null ? undefined : json['cron_schedule'],
        'isVisible': json['is_visible'] == null ? undefined : json['is_visible'],
    };
}

export function CreateSavedSearchParametersToJSON(json: any): CreateSavedSearchParameters {
    return CreateSavedSearchParametersToJSONTyped(json, false);
}

export function CreateSavedSearchParametersToJSONTyped(value?: CreateSavedSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'search': value['search'],
        'description': value['description'],
        'earliest_time': value['earliestTime'],
        'latest_time': value['latestTime'],
        'app': value['app'],
        'sharing': value['sharing'],
        'is_scheduled': value['isScheduled'],
        'cron_schedule': value['cronSchedule'],
        'is_visible': value['isVisible'],
    };
}

