/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateKvstoreCollectionParameters
 */
export interface CreateKvstoreCollectionParameters {
    /**
     * 
     * @type {string}
     * @memberof CreateKvstoreCollectionParameters
     */
    app: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKvstoreCollectionParameters
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKvstoreCollectionParameters
     */
    fields?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateKvstoreCollectionParameters
     */
    acceleratedFields?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateKvstoreCollectionParameters
     */
    replicated?: boolean;
}

/**
 * Check if a given object implements the CreateKvstoreCollectionParameters interface.
 */
export function instanceOfCreateKvstoreCollectionParameters(value: object): value is CreateKvstoreCollectionParameters {
    if (!('app' in value) || value['app'] === undefined) return false;
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function CreateKvstoreCollectionParametersFromJSON(json: any): CreateKvstoreCollectionParameters {
    return CreateKvstoreCollectionParametersFromJSONTyped(json, false);
}

export function CreateKvstoreCollectionParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateKvstoreCollectionParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'],
        'collection': json['collection'],
        'fields': json['fields'] == null ? undefined : json['fields'],
        'acceleratedFields': json['accelerated_fields'] == null ? undefined : json['accelerated_fields'],
        'replicated': json['replicated'] == null ? undefined : json['replicated'],
    };
}

export function CreateKvstoreCollectionParametersToJSON(json: any): CreateKvstoreCollectionParameters {
    return CreateKvstoreCollectionParametersToJSONTyped(json, false);
}

export function CreateKvstoreCollectionParametersToJSONTyped(value?: CreateKvstoreCollectionParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
        'collection': value['collection'],
        'fields': value['fields'],
        'accelerated_fields': value['acceleratedFields'],
        'replicated': value['replicated'],
    };
}

