/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSavedSearchParameters
 */
export interface DeleteSavedSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof DeleteSavedSearchParameters
     */
    name: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSavedSearchParameters
     */
    confirm?: boolean;
    /**
     * 
     * @type {string}
     * @memberof DeleteSavedSearchParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof DeleteSavedSearchParameters
     */
    owner?: string;
}

/**
 * Check if a given object implements the DeleteSavedSearchParameters interface.
 */
export function instanceOfDeleteSavedSearchParameters(value: object): value is DeleteSavedSearchParameters {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function DeleteSavedSearchParametersFromJSON(json: any): DeleteSavedSearchParameters {
    return DeleteSavedSearchParametersFromJSONTyped(json, false);
}

export function DeleteSavedSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSavedSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'confirm': json['confirm'] == null ? undefined : json['confirm'],
        'app': json['app'] == null ? undefined : json['app'],
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function DeleteSavedSearchParametersToJSON(json: any): DeleteSavedSearchParameters {
    return DeleteSavedSearchParametersToJSONTyped(json, false);
}

export function DeleteSavedSearchParametersToJSONTyped(value?: DeleteSavedSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'confirm': value['confirm'],
        'app': value['app'],
        'owner': value['owner'],
    };
}

