/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteSavedSearchParameters
 */
export interface ExecuteSavedSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    earliestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    latestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    mode?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecuteSavedSearchParameters
     */
    maxResults?: number;
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecuteSavedSearchParameters
     */
    owner?: string;
}

/**
 * Check if a given object implements the ExecuteSavedSearchParameters interface.
 */
export function instanceOfExecuteSavedSearchParameters(value: object): value is ExecuteSavedSearchParameters {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ExecuteSavedSearchParametersFromJSON(json: any): ExecuteSavedSearchParameters {
    return ExecuteSavedSearchParametersFromJSONTyped(json, false);
}

export function ExecuteSavedSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteSavedSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'earliestTime': json['earliest_time'] == null ? undefined : json['earliest_time'],
        'latestTime': json['latest_time'] == null ? undefined : json['latest_time'],
        'mode': json['mode'] == null ? undefined : json['mode'],
        'maxResults': json['max_results'] == null ? undefined : json['max_results'],
        'app': json['app'] == null ? undefined : json['app'],
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function ExecuteSavedSearchParametersToJSON(json: any): ExecuteSavedSearchParameters {
    return ExecuteSavedSearchParametersToJSONTyped(json, false);
}

export function ExecuteSavedSearchParametersToJSONTyped(value?: ExecuteSavedSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'earliest_time': value['earliestTime'],
        'latest_time': value['latestTime'],
        'mode': value['mode'],
        'max_results': value['maxResults'],
        'app': value['app'],
        'owner': value['owner'],
    };
}

