/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetConfigurationsParameters
 */
export interface GetConfigurationsParameters {
    /**
     * Configuration file name without .conf extension (e.g., 'props', 'transforms', 'inputs', 'outputs', 'server', 'web')
     * @type {string}
     * @memberof GetConfigurationsParameters
     */
    confFile: string;
    /**
     * Specific stanza name within the conf file to retrieve. If not provided, returns all stanzas in the file.
     * @type {string}
     * @memberof GetConfigurationsParameters
     */
    stanza?: string;
}

/**
 * Check if a given object implements the GetConfigurationsParameters interface.
 */
export function instanceOfGetConfigurationsParameters(value: object): value is GetConfigurationsParameters {
    if (!('confFile' in value) || value['confFile'] === undefined) return false;
    return true;
}

export function GetConfigurationsParametersFromJSON(json: any): GetConfigurationsParameters {
    return GetConfigurationsParametersFromJSONTyped(json, false);
}

export function GetConfigurationsParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetConfigurationsParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'confFile': json['conf_file'],
        'stanza': json['stanza'] == null ? undefined : json['stanza'],
    };
}

export function GetConfigurationsParametersToJSON(json: any): GetConfigurationsParameters {
    return GetConfigurationsParametersToJSONTyped(json, false);
}

export function GetConfigurationsParametersToJSONTyped(value?: GetConfigurationsParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'conf_file': value['confFile'],
        'stanza': value['stanza'],
    };
}

