/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetKvstoreDataParameters
 */
export interface GetKvstoreDataParameters {
    /**
     * 
     * @type {string}
     * @memberof GetKvstoreDataParameters
     */
    collection: string;
    /**
     * 
     * @type {string}
     * @memberof GetKvstoreDataParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof GetKvstoreDataParameters
     */
    query?: string;
}

/**
 * Check if a given object implements the GetKvstoreDataParameters interface.
 */
export function instanceOfGetKvstoreDataParameters(value: object): value is GetKvstoreDataParameters {
    if (!('collection' in value) || value['collection'] === undefined) return false;
    return true;
}

export function GetKvstoreDataParametersFromJSON(json: any): GetKvstoreDataParameters {
    return GetKvstoreDataParametersFromJSONTyped(json, false);
}

export function GetKvstoreDataParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetKvstoreDataParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'collection': json['collection'],
        'app': json['app'] == null ? undefined : json['app'],
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function GetKvstoreDataParametersToJSON(json: any): GetKvstoreDataParameters {
    return GetKvstoreDataParametersToJSONTyped(json, false);
}

export function GetKvstoreDataParametersToJSONTyped(value?: GetKvstoreDataParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'collection': value['collection'],
        'app': value['app'],
        'query': value['query'],
    };
}

