/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetLatestFeatureHealthParameters
 */
export interface GetLatestFeatureHealthParameters {
    /**
     * 
     * @type {number}
     * @memberof GetLatestFeatureHealthParameters
     */
    maxResults?: number;
}

/**
 * Check if a given object implements the GetLatestFeatureHealthParameters interface.
 */
export function instanceOfGetLatestFeatureHealthParameters(value: object): value is GetLatestFeatureHealthParameters {
    return true;
}

export function GetLatestFeatureHealthParametersFromJSON(json: any): GetLatestFeatureHealthParameters {
    return GetLatestFeatureHealthParametersFromJSONTyped(json, false);
}

export function GetLatestFeatureHealthParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLatestFeatureHealthParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'maxResults': json['max_results'] == null ? undefined : json['max_results'],
    };
}

export function GetLatestFeatureHealthParametersToJSON(json: any): GetLatestFeatureHealthParameters {
    return GetLatestFeatureHealthParametersToJSONTyped(json, false);
}

export function GetLatestFeatureHealthParametersToJSONTyped(value?: GetLatestFeatureHealthParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_results': value['maxResults'],
    };
}

