/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSavedSearchDetailsParameters
 */
export interface GetSavedSearchDetailsParameters {
    /**
     * 
     * @type {string}
     * @memberof GetSavedSearchDetailsParameters
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GetSavedSearchDetailsParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof GetSavedSearchDetailsParameters
     */
    owner?: string;
}

/**
 * Check if a given object implements the GetSavedSearchDetailsParameters interface.
 */
export function instanceOfGetSavedSearchDetailsParameters(value: object): value is GetSavedSearchDetailsParameters {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function GetSavedSearchDetailsParametersFromJSON(json: any): GetSavedSearchDetailsParameters {
    return GetSavedSearchDetailsParametersFromJSONTyped(json, false);
}

export function GetSavedSearchDetailsParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSavedSearchDetailsParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'app': json['app'] == null ? undefined : json['app'],
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function GetSavedSearchDetailsParametersToJSON(json: any): GetSavedSearchDetailsParameters {
    return GetSavedSearchDetailsParametersToJSONTyped(json, false);
}

export function GetSavedSearchDetailsParametersToJSONTyped(value?: GetSavedSearchDetailsParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'app': value['app'],
        'owner': value['owner'],
    };
}

