/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListSavedSearchesParameters
 */
export interface ListSavedSearchesParameters {
    /**
     * 
     * @type {string}
     * @memberof ListSavedSearchesParameters
     */
    owner?: string;
    /**
     * 
     * @type {string}
     * @memberof ListSavedSearchesParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof ListSavedSearchesParameters
     */
    sharing?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ListSavedSearchesParameters
     */
    includeDisabled?: boolean;
}

/**
 * Check if a given object implements the ListSavedSearchesParameters interface.
 */
export function instanceOfListSavedSearchesParameters(value: object): value is ListSavedSearchesParameters {
    return true;
}

export function ListSavedSearchesParametersFromJSON(json: any): ListSavedSearchesParameters {
    return ListSavedSearchesParametersFromJSONTyped(json, false);
}

export function ListSavedSearchesParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSavedSearchesParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'owner': json['owner'] == null ? undefined : json['owner'],
        'app': json['app'] == null ? undefined : json['app'],
        'sharing': json['sharing'] == null ? undefined : json['sharing'],
        'includeDisabled': json['include_disabled'] == null ? undefined : json['include_disabled'],
    };
}

export function ListSavedSearchesParametersToJSON(json: any): ListSavedSearchesParameters {
    return ListSavedSearchesParametersToJSONTyped(json, false);
}

export function ListSavedSearchesParametersToJSONTyped(value?: ListSavedSearchesParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'owner': value['owner'],
        'app': value['app'],
        'sharing': value['sharing'],
        'include_disabled': value['includeDisabled'],
    };
}

