/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListKvstoreCollectionsParameters
 */
export interface ListKvstoreCollectionsParameters {
    /**
     * 
     * @type {string}
     * @memberof ListKvstoreCollectionsParameters
     */
    app?: string;
}

/**
 * Check if a given object implements the ListKvstoreCollectionsParameters interface.
 */
export function instanceOfListKvstoreCollectionsParameters(value: object): value is ListKvstoreCollectionsParameters {
    return true;
}

export function ListKvstoreCollectionsParametersFromJSON(json: any): ListKvstoreCollectionsParameters {
    return ListKvstoreCollectionsParametersFromJSONTyped(json, false);
}

export function ListKvstoreCollectionsParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListKvstoreCollectionsParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'app': json['app'] == null ? undefined : json['app'],
    };
}

export function ListKvstoreCollectionsParametersToJSON(json: any): ListKvstoreCollectionsParameters {
    return ListKvstoreCollectionsParametersToJSONTyped(json, false);
}

export function ListKvstoreCollectionsParametersToJSONTyped(value?: ListKvstoreCollectionsParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app': value['app'],
    };
}

