/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ManageAppsParameters
 */
export interface ManageAppsParameters {
    /**
     * 
     * @type {string}
     * @memberof ManageAppsParameters
     */
    action: string;
    /**
     * 
     * @type {string}
     * @memberof ManageAppsParameters
     */
    appName: string;
}

/**
 * Check if a given object implements the ManageAppsParameters interface.
 */
export function instanceOfManageAppsParameters(value: object): value is ManageAppsParameters {
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('appName' in value) || value['appName'] === undefined) return false;
    return true;
}

export function ManageAppsParametersFromJSON(json: any): ManageAppsParameters {
    return ManageAppsParametersFromJSONTyped(json, false);
}

export function ManageAppsParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageAppsParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'appName': json['app_name'],
    };
}

export function ManageAppsParametersToJSON(json: any): ManageAppsParameters {
    return ManageAppsParametersToJSONTyped(json, false);
}

export function ManageAppsParametersToJSONTyped(value?: ManageAppsParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': value['action'],
        'app_name': value['appName'],
    };
}

