/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunOneshotSearchParameters
 */
export interface RunOneshotSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof RunOneshotSearchParameters
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof RunOneshotSearchParameters
     */
    earliestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof RunOneshotSearchParameters
     */
    latestTime?: string;
    /**
     * 
     * @type {number}
     * @memberof RunOneshotSearchParameters
     */
    maxResults?: number;
}

/**
 * Check if a given object implements the RunOneshotSearchParameters interface.
 */
export function instanceOfRunOneshotSearchParameters(value: object): value is RunOneshotSearchParameters {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function RunOneshotSearchParametersFromJSON(json: any): RunOneshotSearchParameters {
    return RunOneshotSearchParametersFromJSONTyped(json, false);
}

export function RunOneshotSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunOneshotSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'earliestTime': json['earliest_time'] == null ? undefined : json['earliest_time'],
        'latestTime': json['latest_time'] == null ? undefined : json['latest_time'],
        'maxResults': json['max_results'] == null ? undefined : json['max_results'],
    };
}

export function RunOneshotSearchParametersToJSON(json: any): RunOneshotSearchParameters {
    return RunOneshotSearchParametersToJSONTyped(json, false);
}

export function RunOneshotSearchParametersToJSONTyped(value?: RunOneshotSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'earliest_time': value['earliestTime'],
        'latest_time': value['latestTime'],
        'max_results': value['maxResults'],
    };
}

