/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RunSplunkSearchParameters
 */
export interface RunSplunkSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof RunSplunkSearchParameters
     */
    query: string;
    /**
     * 
     * @type {string}
     * @memberof RunSplunkSearchParameters
     */
    earliestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof RunSplunkSearchParameters
     */
    latestTime?: string;
}

/**
 * Check if a given object implements the RunSplunkSearchParameters interface.
 */
export function instanceOfRunSplunkSearchParameters(value: object): value is RunSplunkSearchParameters {
    if (!('query' in value) || value['query'] === undefined) return false;
    return true;
}

export function RunSplunkSearchParametersFromJSON(json: any): RunSplunkSearchParameters {
    return RunSplunkSearchParametersFromJSONTyped(json, false);
}

export function RunSplunkSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunSplunkSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'query': json['query'],
        'earliestTime': json['earliest_time'] == null ? undefined : json['earliest_time'],
        'latestTime': json['latest_time'] == null ? undefined : json['latest_time'],
    };
}

export function RunSplunkSearchParametersToJSON(json: any): RunSplunkSearchParameters {
    return RunSplunkSearchParametersToJSONTyped(json, false);
}

export function RunSplunkSearchParametersToJSONTyped(value?: RunSplunkSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'query': value['query'],
        'earliest_time': value['earliestTime'],
        'latest_time': value['latestTime'],
    };
}

