/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolCallResponseResult
 */
export interface ToolCallResponseResult {
    /**
     * 
     * @type {Array<object>}
     * @memberof ToolCallResponseResult
     */
    content?: Array<object>;
    /**
     * 
     * @type {boolean}
     * @memberof ToolCallResponseResult
     */
    isError?: boolean;
}

/**
 * Check if a given object implements the ToolCallResponseResult interface.
 */
export function instanceOfToolCallResponseResult(value: object): value is ToolCallResponseResult {
    return true;
}

export function ToolCallResponseResultFromJSON(json: any): ToolCallResponseResult {
    return ToolCallResponseResultFromJSONTyped(json, false);
}

export function ToolCallResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolCallResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
        'isError': json['isError'] == null ? undefined : json['isError'],
    };
}

export function ToolCallResponseResultToJSON(json: any): ToolCallResponseResult {
    return ToolCallResponseResultToJSONTyped(json, false);
}

export function ToolCallResponseResultToJSONTyped(value?: ToolCallResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': value['content'],
        'isError': value['isError'],
    };
}

