/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolListResponseResult } from './ToolListResponseResult';
import {
    ToolListResponseResultFromJSON,
    ToolListResponseResultFromJSONTyped,
    ToolListResponseResultToJSON,
    ToolListResponseResultToJSONTyped,
} from './ToolListResponseResult';

/**
 * 
 * @export
 * @interface ToolListResponse
 */
export interface ToolListResponse {
    /**
     * 
     * @type {string}
     * @memberof ToolListResponse
     */
    jsonrpc?: string;
    /**
     * 
     * @type {ToolListResponseResult}
     * @memberof ToolListResponse
     */
    result?: ToolListResponseResult;
}

/**
 * Check if a given object implements the ToolListResponse interface.
 */
export function instanceOfToolListResponse(value: object): value is ToolListResponse {
    return true;
}

export function ToolListResponseFromJSON(json: any): ToolListResponse {
    return ToolListResponseFromJSONTyped(json, false);
}

export function ToolListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jsonrpc': json['jsonrpc'] == null ? undefined : json['jsonrpc'],
        'result': json['result'] == null ? undefined : ToolListResponseResultFromJSON(json['result']),
    };
}

export function ToolListResponseToJSON(json: any): ToolListResponse {
    return ToolListResponseToJSONTyped(json, false);
}

export function ToolListResponseToJSONTyped(value?: ToolListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jsonrpc': value['jsonrpc'],
        'result': ToolListResponseResultToJSON(value['result']),
    };
}

