/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ToolMetadata
 */
export interface ToolMetadata {
    /**
     * 
     * @type {string}
     * @memberof ToolMetadata
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ToolMetadata
     */
    description?: string;
    /**
     * 
     * @type {object}
     * @memberof ToolMetadata
     */
    inputSchema?: object;
}

/**
 * Check if a given object implements the ToolMetadata interface.
 */
export function instanceOfToolMetadata(value: object): value is ToolMetadata {
    return true;
}

export function ToolMetadataFromJSON(json: any): ToolMetadata {
    return ToolMetadataFromJSONTyped(json, false);
}

export function ToolMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'inputSchema': json['inputSchema'] == null ? undefined : json['inputSchema'],
    };
}

export function ToolMetadataToJSON(json: any): ToolMetadata {
    return ToolMetadataToJSONTyped(json, false);
}

export function ToolMetadataToJSONTyped(value?: ToolMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'inputSchema': value['inputSchema'],
    };
}

