/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ToolMetadata } from './ToolMetadata';
import {
    ToolMetadataFromJSON,
    ToolMetadataFromJSONTyped,
    ToolMetadataToJSON,
    ToolMetadataToJSONTyped,
} from './ToolMetadata';

/**
 * 
 * @export
 * @interface ToolListResponseResult
 */
export interface ToolListResponseResult {
    /**
     * 
     * @type {Array<ToolMetadata>}
     * @memberof ToolListResponseResult
     */
    tools?: Array<ToolMetadata>;
}

/**
 * Check if a given object implements the ToolListResponseResult interface.
 */
export function instanceOfToolListResponseResult(value: object): value is ToolListResponseResult {
    return true;
}

export function ToolListResponseResultFromJSON(json: any): ToolListResponseResult {
    return ToolListResponseResultFromJSONTyped(json, false);
}

export function ToolListResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ToolListResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'tools': json['tools'] == null ? undefined : ((json['tools'] as Array<any>).map(ToolMetadataFromJSON)),
    };
}

export function ToolListResponseResultToJSON(json: any): ToolListResponseResult {
    return ToolListResponseResultToJSONTyped(json, false);
}

export function ToolListResponseResultToJSONTyped(value?: ToolListResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tools': value['tools'] == null ? undefined : ((value['tools'] as Array<any>).map(ToolMetadataToJSON)),
    };
}

