/* tslint:disable */
/* eslint-disable */
/**
 * MCP Server for Splunk API
 * Model Context Protocol server providing Splunk integration tools
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSavedSearchParameters
 */
export interface UpdateSavedSearchParameters {
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    search?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    earliestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    latestTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    isScheduled?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    cronSchedule?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    isVisible?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    app?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateSavedSearchParameters
     */
    owner?: string;
}

/**
 * Check if a given object implements the UpdateSavedSearchParameters interface.
 */
export function instanceOfUpdateSavedSearchParameters(value: object): value is UpdateSavedSearchParameters {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UpdateSavedSearchParametersFromJSON(json: any): UpdateSavedSearchParameters {
    return UpdateSavedSearchParametersFromJSONTyped(json, false);
}

export function UpdateSavedSearchParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSavedSearchParameters {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'search': json['search'] == null ? undefined : json['search'],
        'description': json['description'] == null ? undefined : json['description'],
        'earliestTime': json['earliest_time'] == null ? undefined : json['earliest_time'],
        'latestTime': json['latest_time'] == null ? undefined : json['latest_time'],
        'isScheduled': json['is_scheduled'] == null ? undefined : json['is_scheduled'],
        'cronSchedule': json['cron_schedule'] == null ? undefined : json['cron_schedule'],
        'isVisible': json['is_visible'] == null ? undefined : json['is_visible'],
        'app': json['app'] == null ? undefined : json['app'],
        'owner': json['owner'] == null ? undefined : json['owner'],
    };
}

export function UpdateSavedSearchParametersToJSON(json: any): UpdateSavedSearchParameters {
    return UpdateSavedSearchParametersToJSONTyped(json, false);
}

export function UpdateSavedSearchParametersToJSONTyped(value?: UpdateSavedSearchParameters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'search': value['search'],
        'description': value['description'],
        'earliest_time': value['earliestTime'],
        'latest_time': value['latestTime'],
        'is_scheduled': value['isScheduled'],
        'cron_schedule': value['cronSchedule'],
        'is_visible': value['isVisible'],
        'app': value['app'],
        'owner': value['owner'],
    };
}

