# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateSavedSearchParameters(BaseModel):
    """
    CreateSavedSearchParameters
    """ # noqa: E501
    name: StrictStr
    search: StrictStr
    description: Optional[StrictStr] = '""'
    earliest_time: Optional[StrictStr] = '""'
    latest_time: Optional[StrictStr] = '""'
    app: Optional[StrictStr] = 'None'
    sharing: Optional[StrictStr] = '"user"'
    is_scheduled: Optional[StrictBool] = False
    cron_schedule: Optional[StrictStr] = '""'
    is_visible: Optional[StrictBool] = True
    __properties: ClassVar[List[str]] = ["name", "search", "description", "earliest_time", "latest_time", "app", "sharing", "is_scheduled", "cron_schedule", "is_visible"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateSavedSearchParameters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateSavedSearchParameters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "search": obj.get("search"),
            "description": obj.get("description") if obj.get("description") is not None else '""',
            "earliest_time": obj.get("earliest_time") if obj.get("earliest_time") is not None else '""',
            "latest_time": obj.get("latest_time") if obj.get("latest_time") is not None else '""',
            "app": obj.get("app") if obj.get("app") is not None else 'None',
            "sharing": obj.get("sharing") if obj.get("sharing") is not None else '"user"',
            "is_scheduled": obj.get("is_scheduled") if obj.get("is_scheduled") is not None else False,
            "cron_schedule": obj.get("cron_schedule") if obj.get("cron_schedule") is not None else '""',
            "is_visible": obj.get("is_visible") if obj.get("is_visible") is not None else True
        })
        return _obj


