# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ToolCallRequestParams(BaseModel):
    """
    ToolCallRequestParams
    """ # noqa: E501
    name: StrictStr
    arguments: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["name", "arguments"]

    @field_validator('name')
    def name_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['get_configurations', 'list_apps', 'list_users', 'manage_apps', 'get_splunk_health', 'create_kvstore_collection', 'get_kvstore_data', 'list_kvstore_collections', 'list_indexes', 'list_sources', 'list_sourcetypes', 'create_saved_search', 'delete_saved_search', 'execute_saved_search', 'get_saved_search_details', 'run_splunk_search', 'list_saved_searches', 'run_oneshot_search', 'update_saved_search', 'get_latest_feature_health']):
            raise ValueError("must be one of enum values ('get_configurations', 'list_apps', 'list_users', 'manage_apps', 'get_splunk_health', 'create_kvstore_collection', 'get_kvstore_data', 'list_kvstore_collections', 'list_indexes', 'list_sources', 'list_sourcetypes', 'create_saved_search', 'delete_saved_search', 'execute_saved_search', 'get_saved_search_details', 'run_splunk_search', 'list_saved_searches', 'run_oneshot_search', 'update_saved_search', 'get_latest_feature_health')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolCallRequestParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolCallRequestParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "arguments": obj.get("arguments")
        })
        return _obj


