# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splunk_mcp_client.models.run_splunk_search_parameters import RunSplunkSearchParameters

class TestRunSplunkSearchParameters(unittest.TestCase):
    """RunSplunkSearchParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunSplunkSearchParameters:
        """Test RunSplunkSearchParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunSplunkSearchParameters`
        """
        model = RunSplunkSearchParameters()
        if include_optional:
            return RunSplunkSearchParameters(
                query = '',
                earliest_time = '"-24h"',
                latest_time = '"now"'
            )
        else:
            return RunSplunkSearchParameters(
                query = '',
        )
        """

    def testRunSplunkSearchParameters(self):
        """Test RunSplunkSearchParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
