# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splunk_mcp_client.models.get_kvstore_data_parameters import GetKvstoreDataParameters

class TestGetKvstoreDataParameters(unittest.TestCase):
    """GetKvstoreDataParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetKvstoreDataParameters:
        """Test GetKvstoreDataParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetKvstoreDataParameters`
        """
        model = GetKvstoreDataParameters()
        if include_optional:
            return GetKvstoreDataParameters(
                collection = '',
                app = 'None',
                query = 'None'
            )
        else:
            return GetKvstoreDataParameters(
                collection = '',
        )
        """

    def testGetKvstoreDataParameters(self):
        """Test GetKvstoreDataParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
