# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splunk_mcp_client.models.execute_saved_search_parameters import ExecuteSavedSearchParameters

class TestExecuteSavedSearchParameters(unittest.TestCase):
    """ExecuteSavedSearchParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecuteSavedSearchParameters:
        """Test ExecuteSavedSearchParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecuteSavedSearchParameters`
        """
        model = ExecuteSavedSearchParameters()
        if include_optional:
            return ExecuteSavedSearchParameters(
                name = '',
                earliest_time = 'None',
                latest_time = 'None',
                mode = '"oneshot"',
                max_results = 56,
                app = 'None',
                owner = 'None'
            )
        else:
            return ExecuteSavedSearchParameters(
                name = '',
        )
        """

    def testExecuteSavedSearchParameters(self):
        """Test ExecuteSavedSearchParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
