# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splunk_mcp_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_tools_call_post(self) -> None:
        """Test case for tools_call_post

        Execute MCP Tool
        """
        pass

    def test_tools_list_post(self) -> None:
        """Test case for tools_list_post

        List Available Tools
        """
        pass


if __name__ == '__main__':
    unittest.main()
