# coding: utf-8

"""
    MCP Server for Splunk API

    Model Context Protocol server providing Splunk integration tools

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from splunk_mcp_client.models.create_saved_search_parameters import CreateSavedSearchParameters

class TestCreateSavedSearchParameters(unittest.TestCase):
    """CreateSavedSearchParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSavedSearchParameters:
        """Test CreateSavedSearchParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSavedSearchParameters`
        """
        model = CreateSavedSearchParameters()
        if include_optional:
            return CreateSavedSearchParameters(
                name = '',
                search = '',
                description = '""',
                earliest_time = '""',
                latest_time = '""',
                app = 'None',
                sharing = '"user"',
                is_scheduled = True,
                cron_schedule = '""',
                is_visible = True
            )
        else:
            return CreateSavedSearchParameters(
                name = '',
                search = '',
        )
        """

    def testCreateSavedSearchParameters(self):
        """Test CreateSavedSearchParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
