name: Trigger auto deployment for mcp-for-splunk

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/mcp-for-splunk-AutoDeployTrigger-382b1997-8cec-421b-a7b3-6bbce5c94ab4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.MCPFORSPLUNK_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MCPFORSPLUNK_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MCPFORSPLUNK_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.MCPFORSPLUNK_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.MCPFORSPLUNK_REGISTRY_PASSWORD }}
          containerAppName: mcp-for-splunk
          resourceGroup: dev-mcp-for-splunk
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


